### ISSUE TITLE
TIme Entry - Jira to MavenLInk

### ISSUE THREAD

**Issue by hwilliamson** [AstadiaDigital/Mavenlink_Test_Cases#1]
Time submitted in Jira transfers to Mavenlink.
Edits to submitted time in Jira transfers to Mavenlink
Deletes of submitted time in Jira DOES NOT transfer to Mavenlink.
ANY CHANGES to time in Mavenlink DOES NOT transfer to Jira.

**Comment by MichaelLafond** [comment]
User Stories describe the requirements of the functions you perform in your job.  These will be further broken down into epics and/or stories to assist in your investigation of how MavenLink and Jira can be used to accomplish to best accomplish these tasks.

Each user story is composed of three aspects:
1.  Written description of the story, used for planning and as a reminder
2.  Conversations about the story that serve to flesh out the details of the story
3.  Tests that convey and document details that can be used to determine when a story is complete 

Reference:
[Mountain Goat](https://www.mountaingoatsoftware.com/articles/advantages-of-user-stories-for-requirements)
[Agile Alliance](https://www.agilealliance.org/glossary/user-stories/#q=~(infinite~false~filters~(postType~(~'page~'post~'aa_book~'aa_event_session~'aa_experience_report~'aa_glossary~'aa_research_paper~'aa_video)~tags~(~'user*20stories))~searchTerm~'~sort~false~sortDirection~'asc~page~1))

Our goal is to ensure we  create a minimum viable product which accommodates your requirements in the needed timeframe. Eventually GitHub will be used to capture the feature files to be used in testing the application.
